development:
  adapter: postgresql
  encoding: unicode
  database: happy_shop_development
  pool: 5
  username: 
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: happy_shop_test
  pool: 5
  username: 
  password:

